### PR TITLE
Update to py311

### PR DESCRIPTION
**Pull request by elitap**
Hi Muhammad,
would you consider this PR updating to python 3.11. Monailabel depends on your work and it wont install on python 3.11 as the numpy version in your work does not support 3.11. I tried to do all the steps to upgrade, but did not check if any functionality breaks. I don't think so but you are the expert :-)

Thanks would be great if you could accept it.

### CODE REVIEW

**Comment by masadcv** [comment]
Hi @elitap 
Many thanks for your contribution. Of course such contributions are most welcome.

I am currently away for a conference, should be back starting the third week of October. Will review this then and get back to you with any comments/suggestions.

You might also want to have a look at torchmaxflow library that is based on this code and may need a similar PR contribution if you are interested...

**Comment by masadcv** [comment]
HI @elitap 
Many thanks for your contribution here. 
I did some testing locally, add some necessary changes needed here and also revert some changes that were not needed for this. I am doing a couple of more test on github after which I will release version 0.0.6 that should have support for py3.11. 

Thanks once again for your contribution and for highlighting that these changes are necessary for your work with monai label.

**Comment by masadcv** [comment]
@elitap as you can already see, I have released this. 
I have added a PR to update to v0.0.6 for numpymaxflow in MONAILabel here: https://github.com/Project-MONAI/MONAILabel/pull/1575

**Comment by elitap** [comment]
Hi @masadcv,
awsome, thank you very much for your work and the help:-).

**Pull request merged**
