### PR TITLE
Support python 3.12

### PR DESCRIPTION
**Pull request by SachidanandAlle**

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
@masadcv when we can have artifacts for python 3.12?

https://pypi.org/project/numpymaxflow/#history

**Comment by masadcv** [comment]
This PR was not the right workflow. 
I am working on the correct workflow for python 3.12 release..

**Comment by masadcv** [comment]
Just to update I have the flow working - only one error remains which is in uploading which I hope to have fixed tonight and then release the new version with python 3.12

Here is the failing flow run for that: https://github.com/masadcv/numpymaxflow/actions/runs/11591899971

**Comment by masadcv** [comment]
@SachidanandAlle I have just release v0.0.7 that supports python 3.12
Could you please re-run your tests and report any issue?

**Comment by jamesobutler** [comment]
@masadcv Reviewing https://pypi.org/project/numpymaxflow/0.0.7/#files, no more Whl files for Intel Mac? I see arm64 variants, but not the universal2 variants.

**Comment by SachidanandAlle** [comment]
Looks good.  Thanks for the update.

**Pull request merged**
