### PR TITLE
[ENH] release GIL during execution

### PR DESCRIPTION
**Pull request by turtleizzy**
Release GIL for easier parallelization in Python.
(multithreading can be used instead of multiprocessing).

### CODE REVIEW

**Comment by masadcv** [comment]
Hi @turtleizzy ,

Many thanks for your contribution here. I will check this over the weekend and merge if all looks good. 
Can you also add a PR for the same for torchmaxflow?

**Comment by turtleizzy** [comment]
> Hi @turtleizzy ,
> 
> Many thanks for your contribution here. I will check this over the weekend and merge if all looks good. Can you also add a PR for the same for torchmaxflow?

I will look into it. It seems releasing GIL is as simple as adding a parameter at the binding statement in torch cpp extension.

**Comment by masadcv** [comment]
> I will look into it. It seems releasing GIL is as simple as adding a parameter at the binding statement in torch cpp extension.

Many thanks, you mean releasing using this approach?
https://discuss.pytorch.org/t/releasing-gil-in-c-extension/19464

If you have time, please add PR, otherwise I can sort it out next week.

**Comment by turtleizzy** [comment]
> > I will look into it. It seems releasing GIL is as simple as adding a parameter at the binding statement in torch cpp extension.
> 
> Many thanks, you mean releasing using this approach? https://discuss.pytorch.org/t/releasing-gil-in-c-extension/19464
> 
> If you have time, please add PR, otherwise I can sort it out next week.

Yes, I am thinking of this line. Although I am not sure whether it is a good idea to make whole function call GIL-released, or we should just scope the maxflow execution line to be GIL released.

**Pull request merged**
